# Generated by Django 4.2.12 on 2025-04-28 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_booking_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='car',
            new_name='car_id',
        ),
    ]
